services:
  postgres:
    image: postgres:16
    container_name: movie_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MovieShowDB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redish
    restart: always
    ports:
      - "6380:6379"

volumes:
  postgres_data:
